language: python

python:
  - "3.4"

install:
  - git clone https://github.com/evhub/prisoner.git
  - PYTHONPATH=$PYTHONPATH:$PWD/prisoner

script:
  - python competition

notifications:
  email: false
