language: python

sudo: false

python:
  - "2.7"
  - "3.4"

env:
  - PYTHONPATH="$PYTHONPATH:$PWD/prisoner"

install:
  - git clone https://github.com/evhub/prisoner.git

script:
  - python competition

notifications:
  email: false
